name: Lint

on:
  - workflow_dispatch
  - push
  - pull_request
jobs:
  test:
    name: v${{ matrix.version }} @ ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: [22]
        os: [ubuntu-22.04-ppc64le]
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: 20
          architecture: ppc64le
      - run: npm install
      - run: npm run build
      - run: npm run lint
